[package]
name = "uniquity-finance-products"
version.workspace = true
edition.workspace = true

[dependencies]
lariv-rs = { workspace = true }
uniquity-common = { workspace = true }
uniquity-finance-accounts = { workspace = true }
uniquity-finance-taxes = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
maud = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
rust_decimal = { workspace = true }
tracing = { workspace = true }
