[package]
name = "uniquity-finance-invoices"
version.workspace = true
edition.workspace = true

[dependencies]
lariv-rs = { workspace = true }
uniquity-common = { workspace = true }
uniquity-finance-accounts = { workspace = true }
uniquity-finance-customer = { workspace = true }
uniquity-finance-products = { workspace = true }
uniquity-finance-taxes = { workspace = true }
uniquity-finance-creditnotes = { workspace = true }
uniquity-finance-fiscal-year = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
maud = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
rust_decimal = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
minijinja = { workspace = true }
num2words = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
