use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[derive(DeriveIden)]
enum Currencies {
    Table,
    CreatedAt,
    UpdatedAt,
    Code,
    Name,
    Symbol,
    MinorUnit,
}

const SEED_CURRENCIES: &[(i32, &str, &str, i32)] = &[
    (8, "Lek", "ALL", 2),
    (12, "Algerian Dinar", "DZD", 2),
    (32, "Argentine Peso", "ARS", 2),
    (36, "Australian Dollar", "AUD", 2),
    (44, "Bahamian Dollar", "BSD", 2),
    (48, "Bahraini Dinar", "BHD", 3),
    (50, "Taka", "BDT", 2),
    (51, "Armenian Dram", "AMD", 2),
    (52, "Barbados Dollar", "BBD", 2),
    (60, "Bermudian Dollar", "BMD", 2),
    (64, "Ngultrum", "BTN", 2),
    (68, "Boliviano", "BOB", 2),
    (72, "Pula", "BWP", 2),
    (84, "Belize Dollar", "BZD", 2),
    (90, "Solomon Islands Dollar", "SBD", 2),
    (96, "Brunei Dollar", "BND", 2),
    (104, "Kyat", "MMK", 2),
    (108, "Burundi Franc", "BIF", 0),
    (116, "Riel", "KHR", 2),
    (124, "Canadian Dollar", "CAD", 2),
    (132, "Cabo Verde Escudo", "CVE", 2),
    (136, "Cayman Islands Dollar", "KYD", 2),
    (144, "Sri Lanka Rupee", "LKR", 2),
    (152, "Chilean Peso", "CLP", 0),
    (156, "Yuan Renminbi", "CNY", 2),
    (170, "Colombian Peso", "COP", 2),
    (174, "Comorian Franc", "KMF", 0),
    (188, "Costa Rican Colon", "CRC", 2),
    (192, "Cuban Peso", "CUP", 2),
    (203, "Czech Koruna", "CZK", 2),
    (208, "Danish Krone", "DKK", 2),
    (214, "Dominican Peso", "DOP", 2),
    (222, "El Salvador Colon", "SVC", 2),
    (230, "Ethiopian Birr", "ETB", 2),
    (232, "Nakfa", "ERN", 2),
    (238, "Falkland Islands Pound", "FKP", 2),
    (242, "Fiji Dollar", "FJD", 2),
    (262, "Djibouti Franc", "DJF", 0),
    (270, "Dalasi", "GMD", 2),
    (292, "Gibraltar Pound", "GIP", 2),
    (320, "Quetzal", "GTQ", 2),
    (324, "Guinean Franc", "GNF", 0),
    (328, "Guyana Dollar", "GYD", 2),
    (332, "Gourde", "HTG", 2),
    (340, "Lempira", "HNL", 2),
    (344, "Hong Kong Dollar", "HKD", 2),
    (348, "Forint", "HUF", 2),
    (352, "Iceland Krona", "ISK", 0),
    (356, "Indian Rupee", "INR", 2),
    (360, "Rupiah", "IDR", 2),
    (364, "Iranian Rial", "IRR", 2),
    (368, "Iraqi Dinar", "IQD", 3),
    (376, "New Israeli Sheqel", "ILS", 2),
    (388, "Jamaican Dollar", "JMD", 2),
    (392, "Yen", "JPY", 0),
    (396, "Arab Accounting Dinar", "XAD", 2),
    (398, "Tenge", "KZT", 2),
    (400, "Jordanian Dinar", "JOD", 3),
    (404, "Kenyan Shilling", "KES", 2),
    (408, "North Korean Won", "KPW", 2),
    (410, "Won", "KRW", 0),
    (414, "Kuwaiti Dinar", "KWD", 3),
    (417, "Som", "KGS", 2),
    (418, "Lao Kip", "LAK", 2),
    (422, "Lebanese Pound", "LBP", 2),
    (426, "Loti", "LSL", 2),
    (430, "Liberian Dollar", "LRD", 2),
    (434, "Libyan Dinar", "LYD", 3),
    (446, "Pataca", "MOP", 2),
    (454, "Malawi Kwacha", "MWK", 2),
    (458, "Malaysian Ringgit", "MYR", 2),
    (462, "Rufiyaa", "MVR", 2),
    (480, "Mauritius Rupee", "MUR", 2),
    (484, "Mexican Peso", "MXN", 2),
    (496, "Tugrik", "MNT", 2),
    (498, "Moldovan Leu", "MDL", 2),
    (504, "Moroccan Dirham", "MAD", 2),
    (512, "Rial Omani", "OMR", 3),
    (516, "Namibia Dollar", "NAD", 2),
    (524, "Nepalese Rupee", "NPR", 2),
    (532, "Caribbean Guilder", "XCG", 2),
    (533, "Aruban Florin", "AWG", 2),
    (548, "Vatu", "VUV", 0),
    (554, "New Zealand Dollar", "NZD", 2),
    (558, "Cordoba Oro", "NIO", 2),
    (566, "Naira", "NGN", 2),
    (578, "Norwegian Krone", "NOK", 2),
    (586, "Pakistan Rupee", "PKR", 2),
    (590, "Balboa", "PAB", 2),
    (598, "Kina", "PGK", 2),
    (600, "Guarani", "PYG", 0),
    (604, "Sol", "PEN", 2),
    (608, "Philippine Peso", "PHP", 2),
    (634, "Qatari Rial", "QAR", 2),
    (643, "Russian Ruble", "RUB", 2),
    (646, "Rwanda Franc", "RWF", 0),
    (654, "Saint Helena Pound", "SHP", 2),
    (682, "Saudi Riyal", "SAR", 2),
    (690, "Seychelles Rupee", "SCR", 2),
    (702, "Singapore Dollar", "SGD", 2),
    (704, "Dong", "VND", 0),
    (706, "Somali Shilling", "SOS", 2),
    (710, "Rand", "ZAR", 2),
    (728, "South Sudanese Pound", "SSP", 2),
    (748, "Lilangeni", "SZL", 2),
    (752, "Swedish Krona", "SEK", 2),
    (756, "Swiss Franc", "CHF", 2),
    (760, "Syrian Pound", "SYP", 2),
    (764, "Baht", "THB", 2),
    (776, "Pa’anga", "TOP", 2),
    (780, "Trinidad and Tobago Dollar", "TTD", 2),
    (784, "UAE Dirham", "AED", 2),
    (788, "Tunisian Dinar", "TND", 3),
    (800, "Uganda Shilling", "UGX", 0),
    (807, "Denar", "MKD", 2),
    (818, "Egyptian Pound", "EGP", 2),
    (826, "Pound Sterling", "GBP", 2),
    (834, "Tanzanian Shilling", "TZS", 2),
    (840, "US Dollar", "USD", 2),
    (858, "Peso Uruguayo", "UYU", 2),
    (860, "Uzbekistan Sum", "UZS", 2),
    (882, "Tala", "WST", 2),
    (886, "Yemeni Rial", "YER", 2),
    (901, "New Taiwan Dollar", "TWD", 2),
    (924, "Zimbabwe Gold", "ZWG", 2),
    (925, "Leone", "SLE", 2),
    (926, "Bolívar Soberano", "VED", 2),
    (927, "Unidad Previsional", "UYW", 4),
    (928, "Bolívar Soberano", "VES", 2),
    (929, "Ouguiya", "MRU", 2),
    (930, "Dobra", "STN", 2),
    (933, "Belarusian Ruble", "BYN", 2),
    (934, "Turkmenistan New Manat", "TMT", 2),
    (936, "Ghana Cedi", "GHS", 2),
    (938, "Sudanese Pound", "SDG", 2),
    (940, "Uruguay Peso en Unidades Indexadas (UI)", "UYI", 0),
    (941, "Serbian Dinar", "RSD", 2),
    (943, "Mozambique Metical", "MZN", 2),
    (944, "Azerbaijan Manat", "AZN", 2),
    (946, "Romanian Leu", "RON", 2),
    (947, "WIR Euro", "CHE", 2),
    (948, "WIR Franc", "CHW", 2),
    (949, "Turkish Lira", "TRY", 2),
    (950, "CFA Franc BEAC", "XAF", 0),
    (951, "East Caribbean Dollar", "XCD", 2),
    (952, "CFA Franc BCEAO", "XOF", 0),
    (953, "CFP Franc", "XPF", 0),
    (955, "Bond Markets Unit European Composite Unit (EURCO)", "XBA", 0),
    (956, "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "XBB", 0),
    (957, "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "XBC", 0),
    (958, "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "XBD", 0),
    (959, "Gold", "XAU", 0),
    (960, "SDR (Special Drawing Right)", "XDR", 0),
    (961, "Silver", "XAG", 0),
    (962, "Platinum", "XPT", 0),
    (963, "Codes specifically reserved for testing purposes", "XTS", 0),
    (964, "Palladium", "XPD", 0),
    (965, "ADB Unit of Account", "XUA", 0),
    (967, "Zambian Kwacha", "ZMW", 2),
    (968, "Surinam Dollar", "SRD", 2),
    (969, "Malagasy Ariary", "MGA", 2),
    (970, "Unidad de Valor Real", "COU", 2),
    (971, "Afghani", "AFN", 2),
    (972, "Somoni", "TJS", 2),
    (973, "Kwanza", "AOA", 2),
    (976, "Congolese Franc", "CDF", 2),
    (977, "Convertible Mark", "BAM", 2),
    (978, "Euro", "EUR", 2),
    (979, "Mexican Unidad de Inversion (UDI)", "MXV", 2),
    (980, "Hryvnia", "UAH", 2),
    (981, "Lari", "GEL", 2),
    (984, "Mvdol", "BOV", 2),
    (985, "Zloty", "PLN", 2),
    (986, "Brazilian Real", "BRL", 2),
    (990, "Unidad de Fomento", "CLF", 4),
    (994, "Sucre", "XSU", 0),
    (997, "US Dollar (Next day)", "USN", 2),
    (999, "No currency", "XXX", 0),
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let backend = manager.get_connection().get_database_backend();
        let conn = manager.get_connection();

        for &(code, name, symbol, minor_unit) in SEED_CURRENCIES {
            let insert = Query::insert()
                .into_table(Currencies::Table)
                .columns([
                    Currencies::CreatedAt,
                    Currencies::UpdatedAt,
                    Currencies::Code,
                    Currencies::Name,
                    Currencies::Symbol,
                    Currencies::MinorUnit,
                ])
                .values_panic([
                    Expr::current_timestamp().into(),
                    Expr::current_timestamp().into(),
                    code.into(),
                    name.into(),
                    symbol.into(),
                    minor_unit.into(),
                ])
                .to_owned();
            conn.execute(backend.build(&insert)).await?;
        }

        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
