[package]
name = "uniquity-gandola-manager"
version.workspace = true
edition.workspace = true

[dependencies]
lariv-rs = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
clap = { version = "4", features = ["derive"] }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = "1.3"
maud = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
rune = "0.14"
base64 = "0.22"
