# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-08-11
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --release
